//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP5_Dood.Modeles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservoir
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Type_Huile { get; set; }
        public double Seuil1 { get; set; }
        public double Seuil2 { get; set; }
        public double Seuil3 { get; set; }
        public int ParcId { get; set; }
    
        public virtual Parc Parc { get; set; }
    }
}
